### ISSUE TITLE
On first call, `pyodide config get emscripten_version` returns `Downloading xbuild environment Installing xbuild environment 3.1.27` instead of `3.1.27`

### ISSUE THREAD

**Issue by josephrocca** [pyodide/pyodide#3430]
## 🐛 Bug

In [the docs for out-of-tree builds](https://pyodide.org/en/stable/development/building-and-testing-packages.html#building-and-testing-packages-out-of-tree) it gives this code snippet:

```bash
pip install pyodide-build

git clone https://github.com/emscripten-core/emsdk.git
cd emsdk

PYODIDE_EMSCRIPTEN_VERSION=$(pyodide config get emscripten_version)
./emsdk install ${PYODIDE_EMSCRIPTEN_VERSION}
./emsdk activate ${PYODIDE_EMSCRIPTEN_VERSION}
source emsdk_env.sh
```
But this doesn't work because on the first call, `pyodide config get emscripten_version` outputs this:
```
Downloading xbuild environment
Installing xbuild environment
3.1.27
```
On subsequent calls it returns `3.1.27`.

### To Reproduce

See above.

### Expected behavior

Calls to `pyodide config get emscripten_version` should only ever output the version string such that this command can be reliably used in build automation.

### Environment

- Pyodide Version: Pyodide CLI Version: 0.2.2

### Additional context

As a workaround for build scripts, `pyodide config get emscripten_version` can be called once before actually using it.

**Comment by ryanking13** [comment]
Thanks for the report @josephrocca! I guess we need to be more careful when printing log messages to stdout...

**Comment by agoose77** [comment]
Is this now fixed by https://github.com/pyodide/pyodide/pull/3442

**Comment by ryanking13** [comment]
No, it is not fixed yet. Probably I'll make a fix in a few days, but I got COVID-19 so I'm not in a very good state to code :<

**Comment by hoodmane** [comment]
Hope you feel better soon @ryanking13!

**Comment by agoose77** [comment]
This might be a slightly personal question @ryanking13, but are you doing OK? I hope you have a support network with you. Sending fast-recovery thoughts your way!

**Comment by ryanking13** [comment]
@agoose77 Yeah, I am totally okay, thanks for asking! I am just experiencing some typical omicron symptoms, but it is getting better quickly.
